# Generated by Django 4.0.3 on 2022-07-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time_to_read',
            field=models.IntegerField(default=1, verbose_name='مدت زمان مطالعه به دقیقه'),
            preserve_default=False,
        ),
    ]
